In [34]:
from tensorflow.keras.datasets import mnist, cifar10
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout
import numpy as np
from tensorflow.keras.utils import to_categorical

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
28*28


784

In [6]:
X_train = np.reshape(X_train, (X_train.shape[0], 784))
X_test = np.reshape(X_test, (X_test.shape[0], 784))

In [7]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [8]:
X_train = X_train/255
X_test = X_test/255

In [9]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_test = to_categorical(y_test, n_classes)


In [10]:
y_train.dtype

dtype('float32')

In [11]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [12]:
model = Sequential(name="ann_model")
model.add(Dense(100, input_shape=(784,), activation='relu'))
model.add(Dense(10, activation='softmax'))

In [13]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [14]:
model.fit(X_train, y_train, batch_size=128, epochs=10)

Epoch 1/10
469/469 [==============================] - 2s 4ms/step - loss: 0.3697 - accuracy: 0.8999
Epoch 2/10
469/469 [==============================] - 2s 4ms/step - loss: 0.1764 - accuracy: 0.9487
Epoch 3/10
469/469 [==============================] - 2s 4ms/step - loss: 0.1314 - accuracy: 0.9623
Epoch 4/10
469/469 [==============================] - 2s 4ms/step - loss: 0.1055 - accuracy: 0.9694
Epoch 5/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0867 - accuracy: 0.9747
Epoch 6/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0738 - accuracy: 0.9788
Epoch 7/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0634 - accuracy: 0.9813
Epoch 8/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0539 - accuracy: 0.9843
Epoch 9/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0475 - accuracy: 0.9861
Epoch 10/10
469/469 [==============================] - 2s 4ms/step - loss: 0.0424 - accuracy: 0.9880

In [15]:
model.predict(X_test[0:5])

array([[1.10458643e-07, 6.14559847e-10, 6.35583201e-05, 2.08835423e-04,
        1.22251997e-09, 1.53881050e-08, 4.43774748e-12, 9.99701202e-01,
        1.31194665e-05, 1.31904362e-05],
       [1.38238903e-07, 2.58994010e-06, 9.99900341e-01, 7.27067672e-05,
        3.23768047e-16, 3.21544030e-06, 7.55602514e-07, 6.31871508e-13,
        2.02243191e-05, 4.01554276e-11],
       [1.43154984e-05, 9.96883810e-01, 4.09498491e-04, 9.38869634e-05,
        5.56443811e-05, 4.89812555e-05, 2.22457835e-04, 9.21246421e-04,
        1.29293685e-03, 5.72185963e-05],
       [9.99966860e-01, 3.56291767e-11, 1.07206870e-05, 1.94502459e-08,
        6.26965289e-08, 7.17175865e-08, 2.40347930e-07, 2.03047093e-05,
        8.72365624e-10, 1.71139322e-06],
       [6.20049559e-06, 2.14789239e-07, 8.15725616e-06, 3.39470319e-09,
        9.98200655e-01, 4.29850147e-08, 2.22415656e-06, 2.04000353e-05,
        1.54227400e-05, 1.74662413e-03]], dtype=float32)

In [16]:
y_test[0:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [18]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [19]:
X_train.shape

(60000, 28, 28)

In [20]:
X_train = np.reshape(X_train, (X_train.shape[0], 28, 28, 1))
X_test = np.reshape(X_test, (X_test.shape[0], 28, 28, 1))


In [22]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [23]:
X_train = X_train/255
X_test= X_test/255 

In [24]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_test = to_categorical(y_test, n_classes)

In [27]:
cnnmodel = Sequential(name="cnn_model")
cnnmodel.add(Conv2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', input_shape=(28,28,1), activation='relu'))
cnnmodel.add(MaxPool2D(pool_size=(1,1)))

In [28]:
cnnmodel.add(Flatten())

In [30]:
cnnmodel.add(Dense(100, activation='relu'))
cnnmodel.add(Dense(10, activation='softmax'))

In [32]:
cnnmodel.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam' )

In [33]:
cnnmodel.fit(X_train, y_train, epochs=10, batch_size=128)

Epoch 1/10
469/469 [==============================] - 39s 84ms/step - loss: 1.0650 - accuracy: 0.7171
Epoch 2/10
469/469 [==============================] - 39s 84ms/step - loss: 0.3803 - accuracy: 0.8892
Epoch 3/10
469/469 [==============================] - 40s 85ms/step - loss: 0.3183 - accuracy: 0.9068
Epoch 4/10
469/469 [==============================] - 38s 80ms/step - loss: 0.2829 - accuracy: 0.9170
Epoch 5/10
469/469 [==============================] - 40s 85ms/step - loss: 0.2531 - accuracy: 0.9263
Epoch 6/10
469/469 [==============================] - 40s 85ms/step - loss: 0.2265 - accuracy: 0.9334
Epoch 7/10
469/469 [==============================] - 40s 85ms/step - loss: 0.2010 - accuracy: 0.9407
Epoch 8/10
469/469 [==============================] - 40s 86ms/step - loss: 0.1799 - accuracy: 0.9468
Epoch 9/10
469/469 [==============================] - 40s 84ms/step - loss: 0.1632 - accuracy: 0.9521
Epoch 10/10
469/469 [==============================] - 40s 85ms/step - loss: 0.148

In [36]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [37]:
X_train.shape

(50000, 32, 32, 3)

In [40]:
X_train = X_train.reshape(X_train.shape[0], 32, 32, 3)
X_test = X_test.reshape(X_test.shape[0], 32, 32, 3)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

In [41]:
X_train /= 255
X_test /= 255

In [42]:
n_classes = 10
y_train = to_categorical(y_train, n_classes)
y_test = to_categorical(y_test, n_classes)

In [44]:
cifarmodel = Sequential(name='cifar10_cnn')
cifarmodel.add(Conv2D(50, kernel_size=(3,3), strides=(1,1), padding='same', input_shape=(32,32,3), activation='relu'))


In [45]:
cifarmodel.add(Conv2D(75, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
cifarmodel.add(MaxPool2D(pool_size=(2,2)))
cifarmodel.add(Dropout(0.25))

In [46]:
cifarmodel.add(Conv2D(125, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
cifarmodel.add(MaxPool2D(pool_size=(2,2)))
cifarmodel.add(Dropout(0.25))

In [47]:
cifarmodel.add(Flatten())

In [48]:
cifarmodel.add(Dense(500, activation='relu'))
cifarmodel.add(Dropout(0.4))
cifarmodel.add(Dense(250, activation='relu'))
cifarmodel.add(Dropout(0.3))

In [49]:
cifarmodel.add(Dense(10, activation='softmax'))

In [51]:
cifarmodel.summary()

Model: "cifar10_cnn"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 32, 32, 50)        1400      
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 75)        33825     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 16, 16, 75)        0         
_________________________________________________________________
dropout (Dropout)            (None, 16, 16, 75)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 16, 16, 125)       84500     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 8, 8, 125)         0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 8, 8, 125)         

In [52]:
cifarmodel.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [53]:
cifarmodel.fit(X_train, y_train, batch_size=128, epochs=10)

Epoch 1/10
391/391 [==============================] - 609s 2s/step - loss: 1.5855 - accuracy: 0.4175
Epoch 2/10
391/391 [==============================] - 604s 2s/step - loss: 1.0816 - accuracy: 0.6137
Epoch 3/10
391/391 [==============================] - 601s 2s/step - loss: 0.8887 - accuracy: 0.6910
Epoch 4/10
391/391 [==============================] - 636s 2s/step - loss: 0.7657 - accuracy: 0.7332
Epoch 5/10
391/391 [==============================] - 620s 2s/step - loss: 0.6868 - accuracy: 0.7631
Epoch 6/10
391/391 [==============================] - 634s 2s/step - loss: 0.6136 - accuracy: 0.7871
Epoch 7/10
391/391 [==============================] - 647s 2s/step - loss: 0.5585 - accuracy: 0.8044
Epoch 8/10
391/391 [==============================] - 605s 2s/step - loss: 0.5104 - accuracy: 0.8194
Epoch 9/10
391/391 [==============================] - 641s 2s/step - loss: 0.4644 - accuracy: 0.8363
Epoch 10/10
391/391 [==============================] - 637s 2s/step - loss: 0.4270 - accura

In [54]:
cifarmodel.save('cifar10.h5')

In [55]:
cifarmodel.save('cifar10')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: cifar10/assets
